/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 animated-rigged-humanCharacter.gltf 
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
// import { useSnapshot } from 'valtio'
// import state from '../store'

export function MaleModel(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/avatarModels/male/male.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  // const snap = useSnapshot(state)

  // Apply the color from the state to the material
  materials['default'].color.set('red')

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[0, 0, 0]} scale={0.8}>
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone007} />
          <primitive object={nodes.Bone008} />
          <skinnedMesh name="FinalBaseMesh" geometry={nodes.FinalBaseMesh.geometry} material={materials['default']} skeleton={nodes.FinalBaseMesh.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/male.gltf')
