/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ShirtModel.gltf 
*/


import { useGLTF } from "@react-three/drei";
// import { useSnapshot } from "valtio";
import { useFrame } from '@react-three/fiber';
import { Decal, useTexture } from '@react-three/drei';

// import state from "../store";

export function ShirtModel(props) {
  // const snap = useSnapshot(state);
  const { nodes, materials } = useGLTF("/clothingModels/shirt/ShirtModel.gltf");

  // const logoTexture = useTexture(snap.logoDecal);

  // Apply the color from the state to the material
  // console.log("Current shirt color:", snap.shirtColor);
  // materials.lambert1.color.set(snap.shirtColor);

  // const stateString = JSON.stringify(snap);

  return (
    <group {...props} dispose={null}  position={[0, 0.2, 0]} scale={3}>
      <mesh
        geometry={nodes.T_Shirt_male.geometry}
        material={materials.lambert1}
      >

      </mesh>
    </group>
  );
}

useGLTF.preload("/ShirtModel.gltf");
